Main svc
panovaaolga/java-explore-with-me pull request #2
Opened 2024-01-22 21:54 UTC by panovaaolga

2024-01-24 08:09 UTC, db-exp requested changes

2024-01-24 08:09 UTC, db-exp commented on stats/service/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +            throw new ForbiddenDateException();
forbidden оно обычно про доступ, а тут скорее bad 400 код

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS public.events (
varchar потерял размерность

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/user/dto/UserShortDto.java
> +    @NotBlank(message = "Класс: UserShortDto. Поле: name. Причина: NotBlank")
можно и size к NotBlank

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/user/dto/UserDto.java
> +public class UserDto {
к NotBlank можно сразу Size добавлять

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/exceptions/ExceptionHandlerEwm.java
> +    public ResponseEntity<Object> handleForbiddenConditions(Exception ex) {
обычно такое исключение не ловят в обработчике, а стараются на этапе валидации запроса отбросить некорректные данные

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/event/dto/EventShortDto.java
> +    private String annotation;
+ size можно

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/event/dto/EventRequestStatusUpdateRequest.java
> +    @NotNull
оба ставить избыточно - достаточно NotEmpty в этом случае

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/event/dto/EventFullDto.java
> +public class EventFullDto {
можно size к NotBlank

2024-01-24 08:09 UTC, db-exp commented on main-service/src/main/java/ru/practicum/compilation/dto/CompilationDto.java
> +    @NotBlank(message = "Класс: CompilationDto. Поле: title. Причина: NotBlank")
можно size

2024-01-24 10:19 UTC, panovaaolga commented on stats/service/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +            throw new ForbiddenDateException();
У меня отдается код 400 при выбросе этого исключения, переименую класс исключения

2024-01-24 12:05 UTC, panovaaolga commented on main-service/src/main/java/ru/practicum/exceptions/ExceptionHandlerEwm.java
> +    public ResponseEntity<Object> handleForbiddenConditions(Exception ex) {
По сути этот метод у меня используется для 2 ситуаций: когда есть нарушение unique key для name или title и для удаления непустой категории, для всех остальных случаев у меня есть проверки. С категорией я исправлю, добавлю проверку. А для unique key я не думала, что нужно добавлять обработку, потому что в примерах ошибок в swagger это давалось в таком виде.

2024-01-26 06:05 UTC, db-exp approved these changes

2024-01-26 06:05 UTC, db-exp commented on main-service/src/main/resources/schema.sql
> +	state varchar NOT NULL,
тут все еще 255

2024-01-26 07:15 UTC, merged